### ISSUE TITLE
Problem - Tivoli Enterprise Portal 

### ISSUE THREAD

**Issue by fernandofreitasti** [rafal-szypulka/grafana-ibm-apm#29]
Please include this information:

- What Grafana version are you using?
  6.6.2

- What IBM APM datasource version are you using and how you installed it (git clone/downloaded git release/grafana-cli) ?
  Revision: 0.8 and made an update made available on the 23rd  

- What OS are you running grafana on?
  SUSE Linux Enterprise Server 12

- What did you do?
  the datasource was configured and the available dashboards were imported
     

- What was the expected result?
  The expected result was that the consultations were lost in the TEP
  
  
   
- What happened instead?
  After configuring the datasource it was possible to consult the metrics in the TEP, 
  but we are having performance problems and the return of queries has been taking longer than normal
  

- If related to metric query / query editor:
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by fernandofreitasti** [comment]
![Grafana_Consulting](https://user-images.githubusercontent.com/44898142/75477988-e53c3880-597b-11ea-95ef-7b557a03ac70.PNG)
![Grafana_Consulting2](https://user-images.githubusercontent.com/44898142/75477990-e9685600-597b-11ea-88f6-28da7c527b4d.PNG)
![Grafana1](https://user-images.githubusercontent.com/44898142/75477991-ea998300-597b-11ea-8a58-643b1af37ea1.png)
![Grafana2](https://user-images.githubusercontent.com/44898142/75477992-eb321980-597b-11ea-8eba-3278c683bcae.png)

**Comment by fernandofreitasti** [comment]
The problem occurred when the chart was updated to a new version

**Comment by rafal-szypulka** [comment]
Just to make sure if I understood correctly. You upgraded the plugin to 0.9 (cloned from Github) and after that, you had some issues with existing dashboards that worked well in the previous version? Is it correct?
First of all, the new version is experimental and try it only in test env. I do not guarantee that old dashboards will just work without any modifications because I added some new features. If you see problems with specific panels, you need to edit the panel and check its configuration. 
1. If the panel shows real-time data in a table or bar chart, make sure that you select "Time Range: Current value". 
2. Try to switch from "Value Attribute" from `value` to `displayValue`
3. Check the `Format` setting. `Table` is only for table panels, but old table panels won't work properly with the new table format and most probably you need to recreate your table panels. If you want to still use old table panels, switch the format to `timeserie`.

**Comment by fernandofreitasti** [comment]
The problem started to occur after the Grafana update. An update to the plugin was an attempt to correct the problems.

**Comment by desscartes** [comment]
I have the same issue abouth my dahsboards,
but  I have very slow perfosmance plus that ıssue. I try to change all dashboards but slowness is a big problem for this.

when I downgrade my plugins 0.8 it works. But with 0.8 it kills my teps service on teps server. I have to find a way for use 0.9 because this issue.

how can we use 0.9 plugin? Am ı create all dashboards like new instalations?

**Comment by fernandofreitasti** [comment]
Hello desscartes,


in my case as a workaround I created a separate TEP, just for graphana. This helped improve performance.

I have a TEP for user access and one only for Grafana, where I create the dashboards.

**Comment by desscartes** [comment]
Hello Fernando,

Thanks 

But now I have only 4 user on my teps. 
Actually my real problem My RestAPI  lock when I call different times on my grafana graphs.
After that I have to restart my teps service (cq).
If I ceate a seperate TEP just grafana is it solution for me? Do you have any lock when you use grafana dashboards?

Thanks,
Cenk

**Comment by fernandofreitasti** [comment]
In my case, you had approximately 100 users who use TEP.



Check if nginx is configured correctly and the call referrer "" is passing, a problem that occurred after configuring nginx.

**Comment by desscartes** [comment]
Thanks ,
I have an nginx confıguratıon like that for call referrer:

```
location /{
           proxy_pass http://localhost:3000/;
           proxy_Set_header Refer "";
        }
```

Is your lock problem's reason nginx configuration?

Now are you using 0.9 plugins with no error or lock?

**Comment by fernandofreitasti** [comment]
I had a problem with nginx but after I fixed it it is normal.

My plugin is working without error, since the creation of TEP just for him.

**Comment by desscartes** [comment]
I checked my teps system.out.logs but there is no "Rejecting rewquest due to invalid Referer attribute" logs. I have just nginix logs like below;
"** upstream timed out (110:Connection timed out) while reading response header from upstream."

and on grafana page I have error like that.

"Panel randerıng error. can not read property 'prefix' or un defined"

**Comment by rafal-szypulka** [comment]
@fernandofreitasti sorry for the late reply. Is the issue solved now? @desscartes make sure that "Deallocate dataset... " option in the datasource config is **enabled** (this option seems to be disabled by default on 0.9 (my mistake))

**Comment by fernandofreitasti** [comment]
It was solved, I created a dedicated TEP and it's working well

**Comment by desscartes** [comment]
Hello Rafal,

At least I increase Heap Size again to 6 gb, it seems ok but I have still continue testing it.

thanks for your helps.

**Comment by ruohki** [comment]
Id like to piggyback on the issue.
I increased the Heap size to 8gb (the ITM system only monitors 1 NT agent right now). Also i did setup a nginx to clear out the referer. Still no luck - after a couple of reads the portal server just freezes and i have to restart the whole vm
